### ISSUE TITLE
AWS Lambda node 8.10 deprecation

### ISSUE THREAD

**Issue by joe-norman** [thundra-io/thundra-examples-lambda-nodejs#12]
Lambda will no longer run new functions with a Node 8.10 runtime, which affects several of the examples, including this template:
 thundra-examples-lambda-nodejs/thundra-sam-mobilebackend/deploy.yml

**Comment by serkan-ozal** [comment]
Fixed by https://github.com/thundra-io/thundra-examples-lambda-nodejs/commit/2bc00f9ba743e769bed61b83ad398a2309265476
